version: '2'
services:
  myapplication-app:
    image: myapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://myapplication-mysql:3306/myapplication?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://myapplication-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://myapplication-elasticsearch:9200
      - KAFKA_BOOTSTRAPSERVERS=kafka:9092
    ports:
      - 8080:8080
  myapplication-mysql:
    extends:
      file: mysql.yml
      service: myapplication-mysql
  myapplication-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: myapplication-elasticsearch
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
